indexed_response_types:
  biosample:
    collection: biosamples
  individual:
    collection: individuals
  variant:
    collection: variants
  analysis:
    collection: callsets

indexed_special_collections:
  collations:
    id:
      db_key: id
    code:
      db_key: code
    child_terms:
      db_key: child_terms
    collation_type:
      db_key: collation_type
    scope:
      db_key: scope
    count:
      db_key: count
    code_matches:
      db_key: code_matches
  frequencymaps:
    id:
      db_key: id

indexed_special_dbs:

  progenetix:
    publications:
      id:
        db_key: id
      pubmedid:
        db_key: pubmedid
      ccgh_count:
        db_key: counts.ccgh
      acgh_count:
        db_key: counts.acgh
      wes_count:
        db_key: counts.wes
      wgs_count:
        db_key: counts.wgs
      genomes_count:
        db_key: counts.genomes
      geoprov_city:
        db_key: provenance.geo_location.properties.city
      geoprov_country:
        db_key: provenance.geo_location.properties.country
      geoprov_iso_alpha3:
        db_key: provenance.geo_location.properties.ISO3166alpha3

    ontologymaps:
      id:
        db_key: id
      code_group_id:
        db_key: code_group.id
      code_group_label:
        db_key: code_group.label

  _byconHousekeepingDB:
    querybuffer:
      id:
        db_key: id
      target_count:
        db_key: target_count
    beaconinfo:
      date:
        db_key: date

  _byconServicesDB:
    genes:
      symbol:
        db_key: symbol
      synonyms:
        db_key: synonyms
      start:
        db_key: start
      end:
        db_key: end




