defaults:
  method: counts
  response_entity_id: collation
method_keys:
  details: []
  counts:
    - id
    - label
    - count
    - code_matches
    - cnv_analyses
    - collation_type
    - type
    - reference
  ids:
    - id
    - label
