defaults:
  response_entity_id: gene
meta:
  received_request_summary:
    assembly_id: GRCh38
    requested_schemas:
      - entity_type: gene
        schema: https://progenetix.org/services/schemas/ProgenetixGene
  info: >
    The main genes payload can be accessed in `response.results`.
assembly_ids:
  - GRCh38
method_keys:
  genespan:
    - symbol
    - reference_name
    - start
    - end
    - accession_version
    - cytobands
